
$files = Get-ChildItem -Path "c:\xampp\htdocs\gopalsdiary\files" -Filter "*.html"

$template = @'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{TITLE}} - Gopals Diary</title>
    <!-- Google Fonts & Icons -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Flutter-like Styling -->
    <link rel="stylesheet" href="bangla_style.css?v=1.2">
</head>
<body>
    <!-- App Bar -->
    <header class="app-bar">
        <div class="app-bar-content">
            <span class="material-icons" style="margin-right: 20px; cursor: pointer;">menu</span>
            <h1 class="app-title">Gopals Diary</h1>
            <div class="spacer"></div>
            <a href="../index.html" class="icon-button" aria-label="Home">
                <span class="material-icons">home</span>
            </a>
        </div>
    </header>

    <main class="container">
        <!-- Gallery Grid -->
        <div id="gallery" class="gallery-grid">
            <!-- Photos will be loaded here by bangla_script.js -->
        </div>
        
        <!-- Loading Indicator -->
        <div id="loading" class="loading-indicator">
            <div class="circular-progress"></div>
            <p style="margin-top: 10px; color: #666;">Loading photos...</p>
        </div>

        <!-- Pagination -->
        <div class="pagination-container">
            <button id="prevBtn" class="fab mini" aria-label="Previous Page">
                <span class="material-icons">chevron_left</span>
            </button>
            <div id="pageNumbers" class="page-numbers">
                <!-- Page numbers generated by JS -->
            </div>
            <button id="nextBtn" class="fab mini" aria-label="Next Page">
                <span class="material-icons">chevron_right</span>
            </button>
        </div>
    </main>

    <!-- Lightbox Overlay -->
    <div id="lightbox" class="lightbox-overlay">
        <div class="lightbox-content">
            <button class="close-btn" onclick="closeLightbox()" aria-label="Close">
                <span class="material-icons">close</span>
            </button>
            
            <div class="lightbox-image-wrapper">
                 <img id="lightboxImage" src="" alt="View">
                 <button class="nav-btn prev" onclick="prevImage()">
                    <span class="material-icons">arrow_back</span>
                 </button>
                 <button class="nav-btn next" onclick="nextImage()">
                    <span class="material-icons">arrow_forward</span>
                 </button>
            </div>
            
            <div class="lightbox-details">
                <h2 id="lightboxTitle">Title</h2>
                <div class="lightbox-controls">
                     Image <span id="imageCounter">1</span> of <span id="totalCounter">100</span>
                </div>
                <p id="lightboxDescription">Description goes here...</p>
                
                <div style="margin-top: auto;">
                    <button class="btn-download" onclick="downloadImage()">
                        <span class="material-icons">download</span> Download
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Configuration & Logic -->
    <script>
        // Configuration for bangla_script.js
        window.TABLE_NAME = '{{TABLE_NAME}}';
        window.PHOTOS_PER_PAGE = 100; // Requested: 100 per page
    </script>
    <script src="bangla_script.js?v=1.2"></script>
</body>
</html>
'@

foreach ($file in $files) {
    if ($file.Name -eq "home.html" -or $file.Name -eq "index.html") { continue }
    
    $tableName = $file.BaseName
    $title = $tableName -replace "_", " "
    $title = (Get-Culture).TextInfo.ToTitleCase($title)
    
    $content = $template -replace "{{TABLE_NAME}}", $tableName
    $content = $content -replace "{{TITLE}}", $title
    
    Set-Content -Path $file.FullName -Value $content -Encoding UTF8
    Write-Host "Updated $($file.Name)"
}
